# Generated by Django 6.0.4 on 2026-04-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
