# Generated by Django 6.0.4 on 2026-04-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='cor',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
    ]
