# Generated by Django 6.0.4 on 2026-04-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_categoria_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cor',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
    ]
