# Generated by Django 6.0.4 on 2026-05-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_autor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='nome_exibicao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
