# Generated by Django 6.0.4 on 2026-05-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_autor_nome_exibicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nome_exibicao',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
