# Generated by Django 6.0.4 on 2026-05-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_autor_nome_exibicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desistiu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='visibilidade',
            field=models.CharField(choices=[('privado', 'Privado'), ('campo', 'Campo das Ideias')], default='privado', max_length=10),
        ),
    ]
