# Generated by Django 6.0.4 on 2026-05-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_desistiu_post_visibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibilidade',
            field=models.CharField(choices=[('privado', 'Privado'), ('feed', 'Feed de Ideias'), ('universo', 'Campo das Ideias')], default='privado', max_length=10),
        ),
    ]
