# Generated by Django 6.0.4 on 2026-05-04 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_visibilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor_original',
            field=models.ForeignKey(blank=True, help_text='Preservado quando autor desiste e moderador assume', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_criados_originalmente', to='posts.autor'),
        ),
        migrations.AddField(
            model_name='post',
            name='limite_moderadores',
            field=models.PositiveIntegerField(default=5, help_text='Limite de moderadores que o autor pode indicar'),
        ),
        migrations.AddField(
            model_name='post',
            name='procura_moderador',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CandidaturaModerador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(blank=True, help_text='Mensagem de apresentação do candidato')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='pendente', max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='posts.autor')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='posts.post')),
            ],
            options={
                'unique_together': {('post', 'candidato')},
            },
        ),
        migrations.CreateModel(
            name='ModeradorPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('moderador', 'Moderador'), ('dono', 'Dono')], default='moderador', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderacoes', to='posts.autor')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderadores', to='posts.post')),
            ],
            options={
                'unique_together': {('post', 'autor')},
            },
        ),
    ]
