# Generated by Django 6.0.4 on 2026-05-05 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_autor_original_post_limite_moderadores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='foto_capa',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/capa/'),
        ),
        migrations.AddField(
            model_name='autor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/perfil/'),
        ),
        migrations.AlterField(
            model_name='candidaturamoderador',
            name='mensagem',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.autor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='autor_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_criados_originalmente', to='posts.autor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='limite_moderadores',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='Seguidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='posts.autor')),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguindo', to='posts.autor')),
            ],
            options={
                'unique_together': {('seguidor', 'seguido')},
            },
        ),
    ]
