# Generated by Django 6.0.4 on 2026-05-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_autor_foto_capa_autor_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderadorpost',
            name='privilegio',
            field=models.CharField(choices=[('novo_dono', 'Novo dono da ideia'), ('edicao_e_moderacao', 'Edição e moderação de comentários'), ('somente_edicao', 'Somente edição'), ('moderacao_comentarios', 'Moderação de comentários')], default='somente_edicao', max_length=30),
        ),
    ]
