# Generated by Django 6.0.4 on 2026-05-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_moderadorpost_privilegio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderadorpost',
            name='privilegio',
            field=models.CharField(choices=[('novo_dono', 'Novo dono da ideia'), ('edicao_e_moderacao', 'Edição e moderação de comentários'), ('somente_edicao', 'Somente edição')], default='somente_edicao', max_length=30),
        ),
    ]
