# Generated by Django 6.0.4 on 2026-05-11 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_moderadorpost_privilegio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('curtida', 'Curtida'), ('clip', 'Clip')], max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='posts.autor')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='posts.post')),
            ],
            options={
                'unique_together': {('post', 'autor', 'tipo')},
            },
        ),
    ]
