# Generated by Django 6.0.4 on 2026-05-11 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_postreacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('curtida', 'Curtida'), ('clip', 'Clip'), ('comentario', 'Comentário'), ('candidatura', 'Candidatura a moderador'), ('eleicao', 'Eleito moderador'), ('recusa', 'Candidatura recusada')], max_length=20)),
                ('lida', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='posts.autor')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='posts.post')),
                ('remetente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_enviadas', to='posts.autor')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
