# Generated by Django 6.0.4 on 2026-05-14 04:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_renomear_universo_para_campo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='categoria',
            name='aprovada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='criada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_criadas', to='posts.autor'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibilidade',
            field=models.CharField(choices=[('privado', 'Privado'), ('feed', 'Feed de Ideias'), ('campo', 'Campo das Ideias')], default='privado', max_length=10),
        ),
    ]
