# Generated by Django 6.0.4 on 2026-05-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_add_criada_por_aprovada_to_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem_capa_1',
            field=models.ImageField(blank=True, null=True, upload_to='posts/capas/'),
        ),
        migrations.AddField(
            model_name='post',
            name='imagem_capa_2',
            field=models.ImageField(blank=True, null=True, upload_to='posts/capas/'),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo_capa',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
