# Generated by Django 6.0.4 on 2026-05-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_fase9_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('curtida', 'Curtida'), ('clip', 'Clip'), ('comentario', 'Comentário'), ('candidatura', 'Candidatura a moderador'), ('eleicao', 'Eleito moderador'), ('recusa', 'Candidatura recusada'), ('seguidor', 'Novo seguidor')], max_length=20),
        ),
    ]
