# Generated by Django 6.0.4 on 2026-05-18 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_notificacao_resposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_cluster', models.FloatField(default=0.0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(related_name='clusters', to='posts.categoria')),
            ],
            options={
                'ordering': ['-score_cluster'],
            },
        ),
        migrations.CreateModel(
            name='CampoInteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direcao', models.CharField(choices=[('up', 'Cima'), ('down', 'Baixo'), ('left', 'Esquerda'), ('right', 'Direita'), ('open', 'Abriu modal')], max_length=10)),
                ('tempo_ms', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes_campo', to='posts.autor')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes_campo', to='posts.post')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ScorePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_cache', to='posts.post')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
