# Generated by Django 6.0.4 on 2026-05-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_fase10_campo_algoritmo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoCardPenalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalidades_campo', to='posts.autor')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalidades_campo', to='posts.post')),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('autor', 'post')},
            },
        ),
    ]
