# Generated by Django 6.0.4 on 2026-06-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_campocardpenalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='canvas_ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='canvas_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='canvas_y',
            field=models.FloatField(default=0.0),
        ),
    ]
