# Generated by Django 6.0.4 on 2026-06-05 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_post_canvas_ordem_post_canvas_x_post_canvas_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('card_ids_ordenados', models.JSONField(default=list)),
                ('canvas_x', models.FloatField(default=0.0)),
                ('canvas_y', models.FloatField(default=0.0)),
                ('canvas_ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='posts.autor')),
                ('cards', models.ManyToManyField(blank=True, related_name='blocos_contendo', to='posts.post')),
            ],
            options={
                'ordering': ['canvas_ordem'],
            },
        ),
    ]
